import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log:
      process.env.NODE_ENV === "development"
        ? ["query", "error", "warn"]
        : ["error"],
  });

if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma;
}

export { PrismaClient };
export * from "@prisma/client";

// Explicitly export enums that may not be included in wildcard export
export type {
  MemberRole,
  Severity,
  EvidenceSource,
  FindingSourceType,
  FindingTargetKind,
  FindingStatus,
  FindingTruthStatus,
  RuleEvaluationKind,
  SuggestionType,
  SuggestionStatus,
  RecipeReviewLevel,
  ReviewType,
  ReviewStatus,
  EvidenceKind,
  EvidenceLifecycleStatus,
  VerificationKind,
  VerificationStatus,
  GovernanceDecisionKind,
  GovernanceDecisionStatus,
  IntegrationType,
  PlanTier,
  SubscriptionStatus,
  CrawlStatus,
  PostCrawlScanKickoffStatus,
  ScanEnqueueFailureCode,
  ScanStatus,
  SiteEnvironment,
  PublicScanStatus,
  CreditTransactionType,
  WebhookSource,
  VisualReviewStatus,
} from "@prisma/client";

// Enums not generated by the Prisma client stub — declared here directly from schema.prisma

export enum SecurityTokenKind {
  PASSWORD_RESET = "PASSWORD_RESET",
  EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
}

export enum AuthLoginMode {
  PASSWORD_AND_SSO = "PASSWORD_AND_SSO",
  SSO_ONLY = "SSO_ONLY",
  PASSWORD_ONLY = "PASSWORD_ONLY",
}

export enum OrgSsoConfigStatus {
  DISABLED = "DISABLED",
  INCOMPLETE = "INCOMPLETE",
  CONFIGURED = "CONFIGURED",
}

/// <reference path="./prisma-types.d.ts" />
