/**
 * Prisma namespace augmentation for types not generated by the local stub.
 *
 * All types here are intentionally permissive (`any`-based) so they compile
 * without breaking runtime behaviour.  Replace individual entries with precise
 * shapes as the generated client becomes available.
 */

// eslint-disable-next-line @typescript-eslint/no-unused-vars
import type { Prisma } from "@prisma/client";

declare module "@prisma/client" {
  // Re-open the Prisma namespace to add missing utility types.
  namespace Prisma {
    // ------------------------------------------------------------------ //
    // ReviewTask
    // ------------------------------------------------------------------ //

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    type ReviewTaskInclude = Record<string, any>;

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    type ReviewTaskUpdateInput = Record<string, any>;

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    type ReviewTaskWhereInput = Record<string, any>;

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    type ReviewTaskGetPayload<_T> = any;

    // ------------------------------------------------------------------ //
    // CanonicalFinding
    // ------------------------------------------------------------------ //

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    type CanonicalFindingDefaultArgs = Record<string, any>;

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    type CanonicalFindingGetPayload<_T> = any;

    // ------------------------------------------------------------------ //
    // Membership
    // ------------------------------------------------------------------ //

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    type MembershipInclude = Record<string, any>;

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    type MembershipGetPayload<_T> = any;

    // ------------------------------------------------------------------ //
    // RemediationSuggestion
    // ------------------------------------------------------------------ //

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    type RemediationSuggestionWhereInput = Record<string, any>;

    // ------------------------------------------------------------------ //
    // Scalar / utility types
    // ------------------------------------------------------------------ //

    /**
     * InputJsonValue — represents any JSON-serialisable value accepted as
     * input to Prisma JSON fields.
     */
    type InputJsonValue =
      | string
      | number
      | boolean
      | null
      | { [key: string]: InputJsonValue }
      | InputJsonValue[];

    // ------------------------------------------------------------------ //
    // Prisma.validator — removed in Prisma 5, re-declared here for
    // compatibility with code that still calls Prisma.validator<T>()(value).
    // ------------------------------------------------------------------ //

    /**
     * `Prisma.validator` shim for Prisma 5 compatibility.
     *
     * Usage (same as Prisma 4):
     *   const myArgs = Prisma.validator<Prisma.SomeArgs>()({ ... });
     */
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    function validator<T = any>(): <V extends T>(value: V) => V;
  }
}
