import { requireSession } from '@/lib/session';
import { prisma } from '@/lib/db';
import { generateReportAction } from './actions';

export const metadata = { title: 'Reports - AROS' };

export default async function ReportsPage() {
  const user = await requireSession();

  const membership = await prisma.membership.findFirst({
    where: { userId: user.id },
  });
  if (!membership) return null;

  const orgId = membership.organizationId;

  const [totalFindings, openFindings, fixedFindings, criticalFindings, sites] = await Promise.all([
    prisma.canonicalFinding.count({
      where: { occurrences: { some: { page: { site: { workspace: { organizationId: orgId } } } } } },
    }),
    prisma.canonicalFinding.count({
      where: {
        status: 'OPEN',
        occurrences: { some: { page: { site: { workspace: { organizationId: orgId } } } } },
      },
    }),
    prisma.canonicalFinding.count({
      where: {
        status: 'FIXED',
        occurrences: { some: { page: { site: { workspace: { organizationId: orgId } } } } },
      },
    }),
    prisma.canonicalFinding.count({
      where: {
        impact: 'CRITICAL',
        status: 'OPEN',
        occurrences: { some: { page: { site: { workspace: { organizationId: orgId } } } } },
      },
    }),
    prisma.site.findMany({
      where: { workspace: { organizationId: orgId } },
      select: { id: true, name: true, domain: true },
    }),
  ]);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-slate-900">Evidence Reports</h1>
        <p className="text-slate-500 mt-1">
          Generate conformance evidence and status reports.
        </p>
      </div>

      <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 text-sm text-amber-800">
        Reports generated by this platform provide evidence of testing and remediation efforts.
        They do not constitute a legal guarantee of WCAG conformance. Full conformance requires
        manual expert review of criteria that cannot be automated.
      </div>

      {/* Summary */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="card">
          <p className="text-sm text-slate-500">Total Findings</p>
          <p className="text-2xl font-bold text-slate-900">{totalFindings}</p>
        </div>
        <div className="card">
          <p className="text-sm text-slate-500">Open</p>
          <p className="text-2xl font-bold text-red-600">{openFindings}</p>
        </div>
        <div className="card">
          <p className="text-sm text-slate-500">Fixed</p>
          <p className="text-2xl font-bold text-green-600">{fixedFindings}</p>
        </div>
        <div className="card">
          <p className="text-sm text-slate-500">Critical Open</p>
          <p className="text-2xl font-bold text-red-700">{criticalFindings}</p>
        </div>
      </div>

      {/* Generate Report */}
      <div className="card">
        <h2 className="text-lg font-semibold text-slate-900 mb-4">Generate Report</h2>
        <form action={generateReportAction} className="space-y-4">
          <div>
            <label htmlFor="report-site" className="label">Site</label>
            <select id="report-site" name="siteId" className="input">
              <option value="">All sites</option>
              {sites.map((site) => (
                <option key={site.id} value={site.id}>
                  {site.name} ({site.domain})
                </option>
              ))}
            </select>
          </div>
          <div>
            <label htmlFor="report-format" className="label">Format</label>
            <select id="report-format" name="format" className="input">
              <option value="json">JSON</option>
              <option value="csv">CSV</option>
            </select>
          </div>
          <button type="submit" className="btn-primary">
            Generate Report
          </button>
        </form>
      </div>
    </div>
  );
}
