import { describe, it, expect } from 'vitest';
import { formatFindingAsMarkdown } from '../github';
import { type AccessibilityFinding } from '../types';

describe('formatFindingAsMarkdown', () => {
  const baseFinding: AccessibilityFinding = {
    id: 'f-1234',
    url: 'https://example.com',
    wcagCriteria: '1.4.3 Contrast (Minimum)',
    severity: 'minor',
    description: 'Text has insufficient color contrast.',
    help: 'Ensure text has a contrast ratio of at least 4.5:1.',
    impact: 'Users with low vision cannot read the text.',
    timestamp: '2023-10-27T10:00:00Z',
    element: 'div.low-contrast'
  };

  it('maps critical severity to 🔴', () => {
    const finding: AccessibilityFinding = { ...baseFinding, severity: 'critical' };
    const markdown = formatFindingAsMarkdown(finding);
    expect(markdown).toContain('🔴 **Severity:** CRITICAL');
  });

  it('maps serious severity to 🟠', () => {
    const finding: AccessibilityFinding = { ...baseFinding, severity: 'serious' };
    const markdown = formatFindingAsMarkdown(finding);
    expect(markdown).toContain('🟠 **Severity:** SERIOUS');
  });

  it('maps moderate severity to 🟡', () => {
    const finding: AccessibilityFinding = { ...baseFinding, severity: 'moderate' };
    const markdown = formatFindingAsMarkdown(finding);
    expect(markdown).toContain('🟡 **Severity:** MODERATE');
  });

  it('maps minor severity to 🔵', () => {
    const finding: AccessibilityFinding = { ...baseFinding, severity: 'minor' };
    const markdown = formatFindingAsMarkdown(finding);
    expect(markdown).toContain('🔵 **Severity:** MINOR');
  });

  it('uses ⚪ for unknown severity', () => {
    const finding = { ...baseFinding, severity: 'unknown' } as unknown as AccessibilityFinding;
    const markdown = formatFindingAsMarkdown(finding);
    expect(markdown).toContain('⚪ **Severity:** UNKNOWN');
  });

  it('includes all fields in the generated markdown', () => {
    const markdown = formatFindingAsMarkdown(baseFinding);
    expect(markdown).toContain('## Accessibility Finding');
    expect(markdown).toContain('Text has insufficient color contrast.');
    expect(markdown).toContain('Ensure text has a contrast ratio of at least 4.5:1.');
    expect(markdown).toContain('Users with low vision cannot read the text.');
    expect(markdown).toContain('| URL | https://example.com |');
    expect(markdown).toContain('| Element | div.low-contrast |');
    expect(markdown).toContain('| WCAG Criteria | 1.4.3 Contrast (Minimum) |');
    expect(markdown).toContain('| Finding ID | f-1234 |');
    expect(markdown).toContain('| Timestamp | 2023-10-27T10:00:00Z |');
    expect(markdown).toContain('*Generated by AccessibleMadeFlexible*');
  });

  it('falls back to "N/A" when element is undefined', () => {
    const findingWithoutElement: AccessibilityFinding = { ...baseFinding, element: undefined };
    const markdown = formatFindingAsMarkdown(findingWithoutElement);
    expect(markdown).toContain('| Element | N/A |');
  });
});
