// Package github provides GitHub integration for issues and actions
import { type GitHubConfig, type CreateGitHubIssuePayload, type GitHubIssue, type AccessibilityFinding } from './types';

const API_BASE = 'https://api.github.com';

/**
 * Create a GitHub issue from accessibility findings
 */
export async function createIssue(
  config: GitHubConfig,
  payload: CreateGitHubIssuePayload
): Promise<GitHubIssue> {
  const { owner, repo, token } = config;

  const response = await fetch(`${API_BASE}/repos/${owner}/${repo}/issues`, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${token}`,
      'Content-Type': 'application/json',
      'Accept': 'application/vnd.github+json'
    },
    body: JSON.stringify({
      title: payload.title,
      body: payload.body,
      labels: payload.labels || ['accessibility', 'a11y'],
      assignees: payload.assignees || []
    })
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Failed to create GitHub issue: ${response.status} - ${error}`);
  }

  return response.json();
}

/**
 * Create issues for multiple accessibility findings
 */
export async function createIssuesForFindings(
  config: GitHubConfig,
  findings: AccessibilityFinding[],
  options?: { batchSize?: number; dryRun?: boolean }
): Promise<{ created: number; issueUrls: string[]; errors: string[] }> {
  const issueUrls: string[] = [];
  const errors: string[] = [];
  let created = 0;
  const batchSize = options?.batchSize || 10;

  for (let i = 0; i < findings.length; i += batchSize) {
    const batch = findings.slice(i, i + batchSize);

    if (options?.dryRun) {
      console.log(`[DRY RUN] Would create ${batch.length} issues`);
      created += batch.length;
      continue;
    }

    for (const finding of batch) {
      const body = formatFindingAsMarkdown(finding);
      const title = `[A11y] ${finding.wcagCriteria}: ${finding.severity}`;

      try {
        const issue = await createIssue(config, { title, body });
        issueUrls.push(issue.html_url);
        created++;
      } catch (error) {
        errors.push(`${finding.id}: ${error instanceof Error ? error.message : 'Unknown error'}`);
      }
    }
  }

  return { created, issueUrls, errors };
}

/**
 * Format an accessibility finding as markdown for GitHub
 */
export function formatFindingAsMarkdown(finding: AccessibilityFinding): string {
  const severityEmoji = {
    critical: '🔴',
    serious: '🟠',
    moderate: '🟡',
    minor: '🔵'
  }[finding.severity] || '⚪';

  return `
## Accessibility Finding

${severityEmoji} **Severity:** ${finding.severity.toUpperCase()}

### Description
${finding.description}

### Help
${finding.help}

### Impact
${finding.impact}

### Details
| Field | Value |
|-------|-------|
| URL | ${finding.url} |
| Element | ${finding.element || 'N/A'} |
| WCAG Criteria | ${finding.wcagCriteria} |
| Finding ID | ${finding.id} |
| Timestamp | ${finding.timestamp} |

---
*Generated by AccessibleMadeFlexible*
  `.trim();
}

/**
 * Add a label to an existing issue
 */
export async function addLabel(
  config: GitHubConfig,
  issueNumber: number,
  labels: string[]
): Promise<void> {
  const { owner, repo, token } = config;

  const response = await fetch(
    `${API_BASE}/repos/${owner}/${repo}/issues/${issueNumber}/labels`,
    {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json',
        'Accept': 'application/vnd.github+json'
      },
      body: JSON.stringify(labels)
    }
  );

  if (!response.ok) {
    throw new Error(`Failed to add label: ${response.status}`);
  }
}

/**
 * Close an issue
 */
export async function closeIssue(
  config: GitHubConfig,
  issueNumber: number
): Promise<void> {
  const { owner, repo, token } = config;

  const response = await fetch(
    `${API_BASE}/repos/${owner}/${repo}/issues/${issueNumber}`,
    {
      method: 'PATCH',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json',
        'Accept': 'application/vnd.github+json'
      },
      body: JSON.stringify({ state: 'closed' })
    }
  );

  if (!response.ok) {
    throw new Error(`Failed to close issue: ${response.status}`);
  }
}
