export interface JiraTicketInput {
  summary: string;
  description: string;
  ruleId: string;
  severity: string;
  affectedPages: string[];
  suggestedFix?: string;
}

/**
 * Formats finding data into a Jira-compatible ticket format.
 * The actual Jira API call would be handled by the integration connection.
 */
export function formatJiraTicket(input: JiraTicketInput): {
  summary: string;
  description: string;
  labels: string[];
  priority: string;
} {
  const priorityMap: Record<string, string> = {
    CRITICAL: 'Highest',
    SERIOUS: 'High',
    MODERATE: 'Medium',
    MINOR: 'Low',
  };

  const pageList = input.affectedPages
    .slice(0, 10)
    .map((url) => `- ${url}`)
    .join('\n');

  const description = [
    `h2. Accessibility Issue: ${input.ruleId}`,
    '',
    input.description,
    '',
    `h3. Severity: ${input.severity}`,
    '',
    'h3. Affected Pages',
    pageList,
    input.affectedPages.length > 10
      ? `_...and ${input.affectedPages.length - 10} more pages_`
      : '',
    '',
    input.suggestedFix
      ? `h3. Suggested Fix\n{code:html}\n${input.suggestedFix}\n{code}`
      : '',
    '',
    '_Generated by AROS - Accessibility Remediation OS_',
    '_Note: This suggestion is AI-generated and requires human review before implementation._',
  ]
    .filter(Boolean)
    .join('\n');

  return {
    summary: `[A11y] ${input.summary}`,
    description,
    labels: ['accessibility', `severity-${input.severity.toLowerCase()}`, input.ruleId],
    priority: priorityMap[input.severity] ?? 'Medium',
  };
}
